# Generated by Django 5.0.7 on 2024-08-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
